"""empty message

Revision ID: 17b5e3e3576d
Revises: 
Create Date: 2017-11-25 10:20:01.072614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b5e3e3576d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stara_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stara_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=6), nullable=True),
    sa.Column('fuel_card_num', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_card_num')
    )
    op.create_table('refuel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('fuel_card_num', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('fuel_volume', sa.Float(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_card_num'], ['vehicles.fuel_card_num'], ),
    sa.ForeignKeyConstraint(['fuel_type'], ['fuel_types.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['fuel_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('boys', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('boys', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boys', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('boys', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_table('refuel_events')
    op.drop_table('vehicles')
    op.drop_table('vehicle_types')
    op.drop_table('fuel_types')
    op.drop_table('fuel_stations')
    # ### end Alembic commands ###
