"""empty message

Revision ID: 54697c9746c3
Revises: e5582f8fe4e7
Create Date: 2017-11-25 21:47:35.022136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54697c9746c3'
down_revision = 'e5582f8fe4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maint_km',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('km_thresh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['vehicle_types.stara_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'vehicles', ['vehicle_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_table('maint_km')
    # ### end Alembic commands ###
