"""empty message

Revision ID: 89aae6dbda42
Revises: 17b5e3e3576d
Create Date: 2017-11-25 12:14:24.760951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aae6dbda42'
down_revision = '17b5e3e3576d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_card_numbers',
    sa.Column('num', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.drop_constraint('refuel_events_fuel_card_num_fkey', 'refuel_events', type_='foreignkey')
    op.create_foreign_key(None, 'refuel_events', 'fuel_card_numbers', ['fuel_card_num'], ['num'])
    op.drop_constraint('vehicles_fuel_card_num_key', 'vehicles', type_='unique')
    op.create_foreign_key(None, 'vehicles', 'fuel_card_numbers', ['fuel_card_num'], ['num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_unique_constraint('vehicles_fuel_card_num_key', 'vehicles', ['fuel_card_num'])
    op.drop_constraint(None, 'refuel_events', type_='foreignkey')
    op.create_foreign_key('refuel_events_fuel_card_num_fkey', 'refuel_events', 'vehicles', ['fuel_card_num'], ['fuel_card_num'])
    op.drop_table('fuel_card_numbers')
    # ### end Alembic commands ###
