"""empty message

Revision ID: aa3b8b425726
Revises: b47a2e68ac94
Create Date: 2017-11-25 22:39:31.009179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa3b8b425726'
down_revision = 'b47a2e68ac94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('km_thresh', sa.Float(), nullable=True),
    sa.Column('days_thresh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['vehicle_types.stara_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maint_km')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maint_km',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('km_thresh', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('days_thresh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type'], ['vehicle_types.stara_id'], name='maint_km_type_fkey'),
    sa.PrimaryKeyConstraint('id', name='maint_km_pkey')
    )
    op.drop_table('maintenance_periods')
    # ### end Alembic commands ###
