"""empty message

Revision ID: b47a2e68ac94
Revises: f74cd80e42d9
Create Date: 2017-11-25 22:25:36.550743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47a2e68ac94'
down_revision = 'f74cd80e42d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maint_km', sa.Column('days_thresh', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maint_km', 'days_thresh')
    # ### end Alembic commands ###
