"""empty message

Revision ID: e5582f8fe4e7
Revises: 99ce0587ab6e
Create Date: 2017-11-25 15:27:27.166966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5582f8fe4e7'
down_revision = '99ce0587ab6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=6), nullable=True),
    sa.Column('service_time', sa.DateTime(), nullable=True),
    sa.Column('bill_time', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sehiid', sa.Integer(), nullable=True),
    sa.Column('rtype', sa.Float(), nullable=True),
    sa.Column('total_sum', sa.Float(), nullable=True),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('ssumnovat', sa.Float(), nullable=True),
    sa.Column('unitpr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garage_visits')
    # ### end Alembic commands ###
