"""empty message

Revision ID: f74cd80e42d9
Revises: 54697c9746c3
Create Date: 2017-11-25 21:57:25.596791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74cd80e42d9'
down_revision = '54697c9746c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'garage_visits', 'vehicles', ['vehicle_id'], ['vehicle_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garage_visits', type_='foreignkey')
    # ### end Alembic commands ###
